"""active in User zu Boolean geändert

Revision ID: 24dec3da17d5
Revises: 5edeedb4e0e8
Create Date: 2024-10-25 07:44:56.706540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dec3da17d5'
down_revision = '5edeedb4e0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.INTEGER(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
