"""Speiseplan entfernt, ist obsolet

Revision ID: 2a5b91369ac0
Revises: 46f383e944bf
Create Date: 2024-10-18 11:27:55.465900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5b91369ac0'
down_revision = '46f383e944bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.drop_index('Datum_RezeptkategorieID')
        batch_op.drop_index('speiseplan_rezepte')
        batch_op.drop_index('speiseplan_rezeptkategorien')

    op.drop_table('speiseplan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speiseplan',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Datum', sa.DATE(), nullable=False),
    sa.Column('Stand', sa.DATETIME(), nullable=False),
    sa.Column('RezeptkategorieID', sa.INTEGER(), nullable=True),
    sa.Column('RezeptID', sa.INTEGER(), nullable=True),
    sa.Column('Anmerkung', sa.VARCHAR(length=400), nullable=True),
    sa.ForeignKeyConstraint(['RezeptID'], ['rezepte.ID'], name='speiseplan_rezepte', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['RezeptkategorieID'], ['rezeptkategorien.ID'], name='speiseplan_rezeptkategorien', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.create_index('speiseplan_rezeptkategorien', ['RezeptkategorieID'], unique=False)
        batch_op.create_index('speiseplan_rezepte', ['RezeptID'], unique=False)
        batch_op.create_index('Datum_RezeptkategorieID', ['Datum', 'RezeptkategorieID'], unique=1)

    # ### end Alembic commands ###
