"""Realationen angepasst

Revision ID: 31f4abb42ec1
Revises: 2a5b91369ac0
Create Date: 2024-10-18 11:35:26.857122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f4abb42ec1'
down_revision = '2a5b91369ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.drop_index('ZutatID_AllergenID')
        batch_op.drop_index('zutaten_allergene_allergene')
        batch_op.drop_constraint('zutaten_allergene_zutaten', type_='foreignkey')
        batch_op.drop_constraint('zutaten_allergene_allergene', type_='foreignkey')
        batch_op.create_foreign_key(None, 'zutaten', ['ZutatID'], ['ID'])
        batch_op.create_foreign_key(None, 'allergene', ['AllergenID'], ['ID'])
        batch_op.drop_column('Stand')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('Stand', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('zutaten_allergene_allergene', 'allergene', ['AllergenID'], ['ID'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('zutaten_allergene_zutaten', 'zutaten', ['ZutatID'], ['ID'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('zutaten_allergene_allergene', ['AllergenID'], unique=False)
        batch_op.create_index('ZutatID_AllergenID', ['ZutatID', 'AllergenID'], unique=1)

    # ### end Alembic commands ###
