"""Rezepte

Revision ID: 46f383e944bf
Revises: 4cab04ab6359
Create Date: 2024-10-18 08:03:01.707607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f383e944bf'
down_revision = '4cab04ab6359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_plan_Datum')
        batch_op.create_index(batch_op.f('ix_essensplan_Datum'), ['Datum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essensplan_Datum'))
        batch_op.create_index('ix_meal_plan_Datum', ['Datum'], unique=False)

    # ### end Alembic commands ###
