"""Essensplan.Ausfall von String zu Integer geändert

Revision ID: 4cab04ab6359
Revises: 7de70e4128f7
Create Date: 2024-07-15 10:24:00.369622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cab04ab6359'
down_revision = '7de70e4128f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.alter_column('Ausfall',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.alter_column('Ausfall',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
