"""changed TIMESTAMP to DATETIME

Revision ID: 571d393c3d09
Revises: 687269e38da7
Create Date: 2024-07-09 14:48:20.246693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d393c3d09'
down_revision = '687269e38da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergene', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('rezepte', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('rezepte_zutaten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('rezeptkategorien', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('zutaten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('zutatengruppen', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zutatengruppen', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('zutaten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('rezeptkategorien', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('rezepte_zutaten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('rezepte', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('allergene', schema=None) as batch_op:
        batch_op.alter_column('Stand',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
