"""User Modell angepasst

Revision ID: 5edeedb4e0e8
Revises: a5a00424f3cc
Create Date: 2024-10-24 15:53:32.108679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edeedb4e0e8'
down_revision = 'a5a00424f3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('given_name',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('given_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
