"""init

Revision ID: 687269e38da7
Revises: 
Create Date: 2024-07-09 08:31:25.524231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687269e38da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergene',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Kuerzel', sa.CHAR(length=2), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('Aktiv', sa.INTEGER(), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('Beschreibung', sa.Text(), nullable=True),
    sa.Column('Kommentar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('allergene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergene_Bezeichnung'), ['Bezeichnung'], unique=False)
        batch_op.create_index(batch_op.f('ix_allergene_Kuerzel'), ['Kuerzel'], unique=False)

    op.create_table('einheiten',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Kuerzel', sa.CHAR(length=3), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('Beschreibung', sa.TEXT(), nullable=False),
    sa.Column('Aktiv', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('BasiseinheitID', sa.INTEGER(), nullable=True),
    sa.Column('BasiseinheitFaktor', sa.DECIMAL(precision=16, scale=8), nullable=True),
    sa.Column('Kommentar', sa.Text(), nullable=True),
    sa.Column('Sortierung', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_einheiten_Bezeichnung'), ['Bezeichnung'], unique=False)
        batch_op.create_index(batch_op.f('ix_einheiten_Kuerzel'), ['Kuerzel'], unique=False)

    op.create_table('rezeptkategorien',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('BezeichnungSingular', sa.String(length=50), nullable=False),
    sa.Column('BezeichnungPlural', sa.String(length=50), nullable=False),
    sa.Column('URL', sa.String(length=60), nullable=False),
    sa.Column('Aktiv', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('Ueberarbeitet', sa.INTEGER(), nullable=False),
    sa.Column('Beschreibung', sa.TEXT(), nullable=True),
    sa.Column('Kuerzel', sa.CHAR(length=3), nullable=True),
    sa.Column('Sortierung', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('rezeptkategorien', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rezeptkategorien_BezeichnungPlural'), ['BezeichnungPlural'], unique=False)
        batch_op.create_index(batch_op.f('ix_rezeptkategorien_BezeichnungSingular'), ['BezeichnungSingular'], unique=False)
        batch_op.create_index(batch_op.f('ix_rezeptkategorien_Kuerzel'), ['Kuerzel'], unique=False)
        batch_op.create_index(batch_op.f('ix_rezeptkategorien_URL'), ['URL'], unique=False)

    op.create_table('user',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vorname', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('mail', sa.Text(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('zutatengruppen',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('Aktiv', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('Ueberarbeitet', sa.INTEGER(), nullable=False),
    sa.Column('Kuerzel', sa.CHAR(length=3), nullable=True),
    sa.Column('Sortierung', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('zutatengruppen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zutatengruppen_Bezeichnung'), ['Bezeichnung'], unique=False)
        batch_op.create_index(batch_op.f('ix_zutatengruppen_Kuerzel'), ['Kuerzel'], unique=False)

    op.create_table('rezepte',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Titel', sa.String(length=50), nullable=False),
    sa.Column('Zubereitung', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('Ueberarbeitet', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('KategorieID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['KategorieID'], ['rezeptkategorien.ID'], name='rezepte_rezeptkategorien'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('rezepte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rezepte_Titel'), ['Titel'], unique=False)

    op.create_table('zutaten',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Bezeichnung', sa.String(length=50), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('Ueberarbeitet', sa.INTEGER(), nullable=False),
    sa.Column('Beschreibung', sa.TEXT(), nullable=True),
    sa.Column('GruppeID', sa.INTEGER(), nullable=True),
    sa.Column('Aktiv', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('Sortierung', sa.INTEGER(), nullable=True),
    sa.Column('zutat_quelle', sa.TEXT(), nullable=True),
    sa.Column('zutat_auth', sa.TEXT(), nullable=True),
    sa.Column('zutat_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['GruppeID'], ['zutatengruppen.ID'], name='zutaten_zutatengruppen'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('zutaten', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zutaten_Bezeichnung'), ['Bezeichnung'], unique=False)

    op.create_table('essensplan',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Datum', sa.Date(), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('HauptgerichtRezeptID', sa.INTEGER(), nullable=True),
    sa.Column('BeilageRezeptID', sa.INTEGER(), nullable=True),
    sa.Column('DessertRezeptID', sa.INTEGER(), nullable=True),
    sa.Column('Ausfall', sa.String(length=50), nullable=True),
    sa.Column('Anmerkung', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['BeilageRezeptID'], ['rezepte.ID'], name='essensplan_rezepte_Beilage'),
    sa.ForeignKeyConstraint(['DessertRezeptID'], ['rezepte.ID'], name='essensplan_rezepte_Dessert'),
    sa.ForeignKeyConstraint(['HauptgerichtRezeptID'], ['rezepte.ID'], name='essensplan_rezepte_Hautgericht'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essensplan_Datum'), ['Datum'], unique=False)

    op.create_table('rezepte_zutaten',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('RezeptID', sa.INTEGER(), nullable=False),
    sa.Column('ZutatID', sa.INTEGER(), nullable=False),
    sa.Column('Menge', sa.Double(asdecimal=True), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('Ueberarbeitet', sa.INTEGER(), nullable=False),
    sa.Column('EinheitID', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['EinheitID'], ['einheiten.ID'], name='rezepte_zutaten_einheiten', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['RezeptID'], ['rezepte.ID'], name='rezepte_zutaten_rezepte', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ZutatID'], ['zutaten.ID'], name='rezepte_zutaten_zutaten', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('speiseplan',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('Datum', sa.Date(), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.Column('RezeptkategorieID', sa.INTEGER(), nullable=True),
    sa.Column('RezeptID', sa.INTEGER(), nullable=True),
    sa.Column('Anmerkung', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['RezeptID'], ['rezepte.ID'], name='speiseplan_rezepte', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['RezeptkategorieID'], ['rezeptkategorien.ID'], name='speiseplan_rezeptkategorien', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.create_index('Datum_RezeptkategorieID', ['Datum', 'RezeptkategorieID'], unique=True)
        batch_op.create_index('speiseplan_rezepte', ['RezeptID'], unique=False)
        batch_op.create_index('speiseplan_rezeptkategorien', ['RezeptkategorieID'], unique=False)

    op.create_table('zutaten_allergene',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('ZutatID', sa.INTEGER(), nullable=False),
    sa.Column('AllergenID', sa.INTEGER(), nullable=False),
    sa.Column('Stand', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['AllergenID'], ['allergene.ID'], name='zutaten_allergene_allergene', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ZutatID'], ['zutaten.ID'], name='zutaten_allergene_zutaten', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.create_index('ZutatID_AllergenID', ['ZutatID', 'AllergenID'], unique=True)
        batch_op.create_index('zutaten_allergene_allergene', ['AllergenID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zutaten_allergene', schema=None) as batch_op:
        batch_op.drop_index('zutaten_allergene_allergene')
        batch_op.drop_index('ZutatID_AllergenID')

    op.drop_table('zutaten_allergene')
    with op.batch_alter_table('speiseplan', schema=None) as batch_op:
        batch_op.drop_index('speiseplan_rezeptkategorien')
        batch_op.drop_index('speiseplan_rezepte')
        batch_op.drop_index('Datum_RezeptkategorieID')

    op.drop_table('speiseplan')
    op.drop_table('rezepte_zutaten')
    with op.batch_alter_table('essensplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essensplan_Datum'))

    op.drop_table('essensplan')
    with op.batch_alter_table('zutaten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zutaten_Bezeichnung'))

    op.drop_table('zutaten')
    with op.batch_alter_table('rezepte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rezepte_Titel'))

    op.drop_table('rezepte')
    with op.batch_alter_table('zutatengruppen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zutatengruppen_Kuerzel'))
        batch_op.drop_index(batch_op.f('ix_zutatengruppen_Bezeichnung'))

    op.drop_table('zutatengruppen')
    op.drop_table('user')
    with op.batch_alter_table('rezeptkategorien', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rezeptkategorien_URL'))
        batch_op.drop_index(batch_op.f('ix_rezeptkategorien_Kuerzel'))
        batch_op.drop_index(batch_op.f('ix_rezeptkategorien_BezeichnungSingular'))
        batch_op.drop_index(batch_op.f('ix_rezeptkategorien_BezeichnungPlural'))

    op.drop_table('rezeptkategorien')
    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_einheiten_Kuerzel'))
        batch_op.drop_index(batch_op.f('ix_einheiten_Bezeichnung'))

    op.drop_table('einheiten')
    with op.batch_alter_table('allergene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergene_Kuerzel'))
        batch_op.drop_index(batch_op.f('ix_allergene_Bezeichnung'))

    op.drop_table('allergene')
    # ### end Alembic commands ###
