"""User

Revision ID: 6acdb81dd8d4
Revises: f82823bff5d4
Create Date: 2024-10-27 12:14:09.855601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acdb81dd8d4'
down_revision = 'f82823bff5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user', new_column_name='username')
    # ### end Alembic commands ###


def downgrade():
    op.alter_column('user', 'username', new_column_name='user')

