"""Benutzerfeld von mail in email umbenannt

Revision ID: 8daffbcfe353
Revises: 2477aad50b4e
Create Date: 2024-10-28 11:24:53.509469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daffbcfe353'
down_revision = '2477aad50b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mail', new_column_name='email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email', new_column_name='mail')

    # ### end Alembic commands ###
