"""User Modell angepasst

Revision ID: a5a00424f3cc
Revises: 31f4abb42ec1
Create Date: 2024-10-24 15:38:25.454982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a00424f3cc'
down_revision = '31f4abb42ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('given_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('given_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('given_name', sa.TEXT(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('given_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
