"""user_anpassungen

Revision ID: bec923b6ac5c
Revises: 8cd1058e6dc4
Create Date: 2024-12-04 08:12:28.253201

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bec923b6ac5c'
down_revision = '8cd1058e6dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('level',
                              existing_type=sa.VARCHAR(length=6),
                              type_=sa.Integer(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('level',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(length=6),
                              existing_nullable=True)

    # ### end Alembic commands ###
