"""Change User ID to id

Revision ID: cbd41b3147e1
Revises: 571d393c3d09
Create Date: 2024-07-11 20:38:42.204207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd41b3147e1'
down_revision = '571d393c3d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('mail',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.INTEGER(), nullable=False))
        batch_op.alter_column('mail',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
